### ISSUE TITLE
Issue when running script

### ISSUE THREAD

**Issue by yabbah** [deegan/trnt-scripts#1]
I got this error message when I try to run the script. 
```
Traceback (most recent call last):
  File "./episodeSorter.py", line 105, in <module>
    filename        = str(sys.argv[1])
IndexError: list index out of range
```
Any idea?

**Comment by deegan** [comment]
Fixed some sanity checking. The error is thrown because episodeSorter.py needs some input, like a directory. 

episodeSorter.py {directory}

This commit makes the user aware of this by adding a ERROR and a USAGE notification if you omit the directory when executing the episodeSorter.py script.

https://github.com/deegan/trnt-scripts/commit/0d9b6da1af30955499a2ff5b3f5d1fe687b62822
